[package]
name = "rnbt"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
derive-new = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyo3 = { version = "0.20", features = ["extension-module"] }

[dev-dependencies]
flate2 = "1.0.9"

[lib]
crate-type = ["cdylib"]
